name: Check Formatting

on: pull_request

defaults:
    run:
        shell: bash

jobs:
    clang-format:
        uses: korydraughn/irods_reusable_github_workflows/.github/workflows/linter-irods-clang-format.yml@main
